export const BILLING_SERVICE='BILLING';
export const HISTORY_SERVICE='HISTORY';

export const WISHLIST_SERVICE='WISHLIST';

export const USER_SERVICE='USER';

export const SETTINGS_SERVICE='SETTINGS';
